# BuildBuddy workflow for building RisingOS ROM (miatoll)
version: 1

actions:
  - name: "RisingOS Build (miatoll)"
    timeout: 72000  # 20 hours (long Android builds)
    environment:
      image: ubuntu:22.04
      shell_commands:
        - |
          apt-get update -y
          apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib \
              g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
              libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo openjdk-11-jdk wget python3 python3-pip
          echo "✅ Environment ready"

          # Configure git
          git config --global user.name "BuildBuddy"
          git config --global user.email "build@bot"

          # Clone the RisingOS manifest and initialize repo
          echo ">>> Initializing repo"
          repo init -u https://github.com/risingosmi/RISINGOS -b 16 --git-lfs

          # Sync source
          echo ">>> Syncing repo"
          repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j$(nproc --all)

          # Clone device-specific repositories
          echo ">>> Cloning device, vendor, kernel, and hardware trees"
          git clone https://github.com/risingosmi/vendor-risingos_priv-keys.git -b 16 vendor/lineage-priv/keys
          git clone https://github.com/risingosmi/device_xiaomi_miatoll.git -b 16 device/xiaomi/miatoll
          git clone https://github.com/risingosmi/vendor_xiaomi_miatoll.git -b 16 vendor/xiaomi/miatoll
          git clone https://github.com/risingosmi/kernel_xiaomi_sm6250.git -b 16 kernel/xiaomi/sm6250
          git clone https://github.com/risingosmi/hardware_xiaomi.git -b 16 hardware/xiaomi
          git clone https://github.com/LineageOS/android_hardware_sony_timekeep.git -b lineage-22.2 hardware/sony/timekeep
          git clone https://github.com/risingosmi/vendor_xiaomi_miuicamera.git -b 16 vendor/xiaomi/miuicamera
          git clone https://github.com/risingosmi/vendor_dolby_miatoll.git -b 16 vendor/sony/dolby

          # Setup environment
          echo ">>> Setting up build environment"
          source build/envsetup.sh

         gk -f

          # Lunch target
          riseup miatoll user

          # Start build
          echo ">>> Building RisingOS ROM..."
          rise b || ./build/soong/soong_ui.bash --make-mode -j$(nproc --all)

          echo "✅ Build completed!"
